# NumPy

In [1]:
import numpy as np

Criando Arrays

In [2]:
vetor = np.array([1, 2, 3, 4, 5, 6])

In [3]:
vetor

array([1, 2, 3, 4, 5, 6])

In [4]:
type(vetor)

numpy.ndarray

In [5]:
vetor2 = np.array((1, 2, 3, 4 , 5, 6))

In [6]:
vetor2

array([1, 2, 3, 4, 5, 6])

In [8]:
matriz = np.array([[10, 15, 20], [25, 30, 35], [40, 45, 50]])

In [9]:
matriz

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [12]:
#range(start, stop, step)

In [11]:
a = range(1, 20)

In [13]:
list(range(1, 21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [14]:
np.arange(1, 21, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [16]:
np.ones(shape = (10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.full(shape= (10,5), fill_value= 15)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [20]:
np.empty((3,2))

array([[1.33511290e-306, 1.11260619e-306],
       [1.37961370e-306, 1.33511561e-306],
       [1.11261027e-306, 3.59412797e-317]])

## Inspecionando Arrays

In [21]:
vetor = np.array([10, 15, 20, 30])

In [22]:
vetor.shape

(4,)

In [23]:
len(vetor)

4

In [24]:
vetor.ndim

1

In [25]:
vetor.size

4

In [26]:
vetor = np.array([15, 10, 44, 90], dtype=float)

In [27]:
vetor

array([15., 10., 44., 90.])

In [28]:
vetor.dtype

dtype('float64')

In [29]:
vetor = vetor.astype(int) #convertendo tipo de dados