# NumPy

In [27]:
import numpy as np

Criando Arrays

In [28]:
vetor = np.array([1, 2, 3, 4, 5, 6])

In [29]:
vetor

array([1, 2, 3, 4, 5, 6])

In [30]:
type(vetor)

numpy.ndarray

In [31]:
vetor2 = np.array((1, 2, 3, 4 , 5, 6))

In [32]:
vetor2

array([1, 2, 3, 4, 5, 6])

In [33]:
matriz = np.array([[10, 15, 20], [25, 30, 35], [40, 45, 50]])

In [34]:
matriz

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [35]:
#range(start, stop, step)

In [36]:
a = range(1, 20)

In [37]:
list(range(1, 21))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [38]:
np.arange(1, 21, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5,
       12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ,
       17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5])

In [39]:
np.ones(shape = (10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [40]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.full(shape= (10,5), fill_value= 15)

array([[15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15],
       [15, 15, 15, 15, 15]])

In [43]:
np.empty((3,2))

array([[1.42873649e-101, 4.94065646e-324],
       [1.76567204e-318, 1.29146288e-125],
       [3.53942267e-314, 1.35897904e-125]])

## Inspecionando Arrays

In [44]:
vetor = np.array([10, 15, 20, 30])

In [45]:
vetor.shape

(4,)

In [46]:
len(vetor)

4

In [47]:
vetor.ndim

1

In [48]:
vetor.size

4

In [49]:
vetor = np.array([15, 10, 44, 90], dtype=float)

In [50]:
vetor

array([15., 10., 44., 90.])

In [51]:
vetor.dtype

dtype('float64')

In [52]:
vetor = vetor.astype(int) #convertendo tipo de dados

Operações Matemáticas

In [53]:
vetor1 = np.array([2, 3, 1])
vetor2 = np.array([1, 3, 2])

In [54]:
soma = vetor2 + vetor1

In [55]:
soma

array([3, 6, 3])

In [56]:
soma = np.add(vetor1, vetor2)

In [57]:
soma

array([3, 6, 3])

In [58]:
sub = vetor1 - vetor2

In [59]:
sub

array([ 1,  0, -1])

In [60]:
np.subtract(vetor1, vetor2)

array([ 1,  0, -1])

In [61]:
vetor1/vetor2

array([2. , 1. , 0.5])

In [62]:
np.divide(vetor1, vetor2)

array([2. , 1. , 0.5])

In [63]:
np.multiply(vetor1, vetor2)

array([2, 9, 2])

In [64]:
vetor1+1

array([3, 4, 2])

In [65]:
vetor-1

array([14,  9, 43, 89])

In [66]:
vetor**2

array([ 225,  100, 1936, 8100])

In [67]:
vetor

array([15, 10, 44, 90])

In [68]:
v = vetor1**1

In [69]:
np.sqrt(v)

array([1.41421356, 1.73205081, 1.        ])

In [70]:
np.sin(vetor1)

array([0.90929743, 0.14112001, 0.84147098])

In [71]:
np.log2(v)

array([1.       , 1.5849625, 0.       ])

In [73]:
matrix1 = np.array([[1,2], [3, 4]])
matrix2 = np.array([[1, 1], [2, 2]])

In [74]:
matrix2

array([[1, 1],
       [2, 2]])

In [75]:
matrix1

array([[1, 2],
       [3, 4]])

In [77]:
matrix1.shape

(2, 2)

In [78]:
matrix2.shape

(2, 2)

In [79]:
matrix1 + matrix2

array([[2, 3],
       [5, 6]])

In [80]:
(4)*matrix1

array([[ 4,  8],
       [12, 16]])

In [81]:
np.dot(matrix1,matrix2)

array([[ 5,  5],
       [11, 11]])

In [82]:
matrix1.dot(matrix2)

array([[ 5,  5],
       [11, 11]])

In [83]:
matrix1 @ matrix2

array([[ 5,  5],
       [11, 11]])

Comparações Lógicas

In [84]:
a = np.array([10, 15, 20])
b = np.array([10, 18, 21])

In [85]:
a == b

array([ True, False, False])

In [86]:
a != b

array([False,  True,  True])

In [87]:
a> b

array([False, False, False])

In [88]:
a < b

array([False,  True,  True])

In [89]:
a <= b

array([ True,  True,  True])

In [90]:
a = np.array([1, 1, 1])
b = np.array([1, 1, 1])

In [91]:
np.array_equal(a, b)

True

Funções de agregação

In [92]:
vetor = np.arange(1, 21)

In [93]:
vetor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [94]:
vetor.min()

1

In [95]:
vetor.max()

20

In [96]:
np.median(vetor)

10.5

In [97]:
vetor.mean()

10.5

In [98]:
np.std(vetor)

5.766281297335398

In [99]:
np.var(vetor)

33.25

In [100]:
matrix = np.array([[2, 11, 15], [20, 21, 17], [90, 15, 13]])

In [102]:
matrix

array([[ 2, 11, 15],
       [20, 21, 17],
       [90, 15, 13]])

In [103]:
np.corrcoef(matrix)

array([[ 1.        , -0.55313398, -0.96041719],
       [-0.55313398,  1.        ,  0.29916848],
       [-0.96041719,  0.29916848,  1.        ]])

Ordenando Arrays